<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'model_name'=>'string',
    'details'=>'string',
    'brand_id'=>'string',
    'deviceType_id'=>'string',
      'model_number'=>'string'
  ];

    public function Parts()
    {
        return $this->hasMany('\App\Models\Part','device_id','id');
    }
    public function WorkOrderDevices()
    {
        return $this->hasMany('\App\Models\WorkOrderDevice','device_id','id');
    }
}
