<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Relations\Pivot;

class DevicePart extends Pivot
{
  /**  
  * Primary key name.
  * 
  * @var string
  */
  public $primaryKey='device_id';
  
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'device_id'=>'string',
    'part_id'=>'string'
  ];
}
