<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class PartMvmntFrom extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'partMovement_id'=>'string',
    'location_id'=>'string',
    'sublocation_id'=>'string'
  ];
  public function PartMovement()
  {
    return $this->belongsTo('\App\Models\PartMovement','partMovement_id','id');
  }
  public function location()
  {
    return $this->belongsTo('\App\Models\Location','location_id','id');
  }
}
