<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class PurchaseOrderPayment extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'transaction_date'=>'datetime',
    'transaction_details'=>'string',
    'amount_CAD'=>'float',
    'amount_USD'=>'float',
    'exchange_rate_to_CAD'=>'float'
  ];
  public function PurchaseOrders()
  {
    return $this->hasMany('\App\Models\PurchaseOrder','purchaseOrderPayment_id','id');
  }
}
