<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class PurchaseOrderDiff extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The model's default values for attributes.
  * 
  * @var array
  */
  protected $attributes=[
    'qty_diff'=>0,
    'value_diff_CAD'=>0,
    'value_diff_USD'=>0
  ];
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'number'=>'string',
    'qty_diff'=>'integer',
    'value_diff_CAD'=>'float',
    'value_diff_USD'=>'float',
    'credit_debit_details'=>'string',
    'purchaseOrder_id'=>'string'
  ];
  public function PurchaseOrder()
  {
    return $this->belongsTo('\App\Models\PurchaseOrder','purchaseOrder_id','id');
  }
  public function PurchaseOrderDiffItems()
  {
    return $this->hasMany('\App\Models\PurchaseOrderDiffItems','purchaseOrderDiff_id','id');
  }
}
