<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class Service extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'name'=>'string',
    'details'=>'string',
    'selling_price_b2b'=>'float',
    'selling_price_b2c'=>'float',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function WODeviceServices()
  {
    return $this->hasMany('\App\Models\WODeviceService','service_id','id');
  }
}
