<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class StockCount extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  protected $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'number'=>'string',
    'started_at'=>'datetime',
    'ended_at'=>'datetime',
    'stockCountStatus_id'=>'string',
    'location_id'=>'string'
  ];
  public function StockCountStatus()
  {
    return $this->belongsTo('\App\Models\StockCountStatus','stockCountStatus_id','id');
  }
  public function Location()
  {
    return $this->belongsTo('\App\Models\Location','location_id','id');
  }
  public function StockCountItemsSeqs()
  {
    return $this->hasMany('\App\Models\StockCountItemsSeq','stockCount_id','id');
  }
  public function StockCountItems()
  {
    return $this->hasMany('\App\Models\StockCountItems','stockCount_id','id');
  }
}
