<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class WODevicePart extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'work_order_device_id'=>'string',
    'part_id'=>'string',
    'part_name'=>'string',
    'part_details'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function WorkOrderDevice()
  {
    return $this->belongsTo('\App\Models\WorkOrderDevice','work_order_device_id','id');
  }
  public function Part()
  {
    return $this->belongsTo('\App\Models\Part','part_id','id');
  }
}
