<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class WorkOrderDevice extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'work_order_id'=>'string',
    'device_id'=>'string',
    'device_details'=>'string',
    'device_type_id'=>'string',
    'issue_description'=>'string',
    'problem'=>'string',
    'solution'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime'
  ];
  public function WorkOrder()
  {
    return $this->belongsTo('\App\Models\WorkOrder','work_order_id','id');
  }
  public function Device()
  {
    return $this->belongsTo('\App\Models\Device','device_id','id');
  }
  public function DeviceType()
  {
    return $this->belongsTo('\App\Models\DeviceType','device_type_id','id');
  }
  public function WODeviceParts()
  {
    return $this->hasMany('\App\Models\WODevicePart','work_order_device_id','id');
  }
  public function WODeviceServices()
  {
    return $this->hasMany('\App\Models\WODeviceService','work_order_device_id','id');
  }
}
