<?php
/* Model object generated by: Skipper (http://www.skipper18.com) */
/* Do not modify this file manually.*/

namespace App\Models\Base;

use Illuminate\Database\Eloquent\Model;

class WorkOrder extends Model
{
  /**  
  * Primary key type.
  * 
  * @var string
  */
  protected $keyType='uuid';
  
  /**  
  * Primary key is non-autoincrementing.
  * 
  * @var bool
  */
  public $incrementing=false;
  
  /**  
  * The attributes that should be cast to native types.
  * 
  * @var array
  */
  protected $casts=[
    'id'=>'string',
    'number'=>'string',
    'created_at'=>'datetime',
    'updated_at'=>'datetime',
      'location_id'=>'string'
  ];
    public function Location()
    {
        return $this->belongsTo('\App\Models\Location','location_id','id');
    }
  public function WorkOrderDevices()
  {
    return $this->hasMany('\App\Models\WorkOrderDevice','work_order_id','id');
  }
}
