<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: f70e0356-be32-4101-96eb-08052dc86e05 */
/* Migration datetime: 2019-03-01 10:50:20.578054 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190301105020 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('stock_count_statuses', function (Blueprint $table) {
      $table->integer('seq_id')->nullable(true)->unique();
    });
    Schema::table('purchase_order_payment_statuses', function (Blueprint $table) {
      $table->integer('seq_id')->nullable(true)->unique();
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('purchase_order_payment_statuses', function (Blueprint $table) {
      $table->dropColumn('seq_id');
    });
    Schema::table('stock_count_statuses', function (Blueprint $table) {
      $table->dropColumn('seq_id');
    });
  }
}
