<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: f82cd9f9-f44c-4cdb-8b9e-e0407eb05829 */
/* Migration datetime: 2019-02-07 10:42:47.203158 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190207104247 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('parts', function (Blueprint $table) {
      $table->dateTime('first_received')->nullable(true);
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('parts', function (Blueprint $table) {
      $table->dropColumn('first_received');
    });
  }
}
