<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: f29f0096-9c1f-475d-ac1d-9ddf6b101afe */
/* Migration datetime: 2019-02-28 12:25:34.854114 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190228122534 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('purchase_order_statuses', function (Blueprint $table) {
      $table->integer('seq_id')->nullable(true)->unique();
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('purchase_order_statuses', function (Blueprint $table) {
      $table->dropColumn('seq_id');
    });
  }
}
