<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: fade70d4-476c-47ca-8c91-a36248454038 */
/* Migration datetime: 2019-02-21 09:40:48.156372 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190221094048 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('brands', function (Blueprint $table) {
      $table->text('description')->nullable(true)->change();
    });
    Schema::table('devices', function (Blueprint $table) {
      $table->text('details')->nullable(true)->change();
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->text('details')->nullable(true)->change();
    });
    Schema::table('locations', function (Blueprint $table) {
      $table->text('description')->nullable(true)->change();
    });
    Schema::table('part_statuses', function (Blueprint $table) {
      $table->text('description')->nullable(true)->change();
    });
    Schema::table('part_categories', function (Blueprint $table) {
      $table->text('details')->nullable(true)->change();
    });
    Schema::table('part_types', function (Blueprint $table) {
      $table->text('details')->nullable(true)->change();
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('part_types', function (Blueprint $table) {
      $table->multiLineString('details')->nullable(true)->change();
    });
    Schema::table('part_categories', function (Blueprint $table) {
      $table->multiLineString('details')->nullable(true)->change();
    });
    Schema::table('part_statuses', function (Blueprint $table) {
      $table->multiLineString('description')->nullable(true)->change();
    });
    Schema::table('locations', function (Blueprint $table) {
      $table->multiLineString('description')->nullable(true)->change();
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->multiLineString('details')->nullable(true)->change();
    });
    Schema::table('devices', function (Blueprint $table) {
      $table->multiLineString('details')->nullable(true)->change();
    });
    Schema::table('brands', function (Blueprint $table) {
      $table->multiLineString('description')->nullable(true)->change();
    });
  }
}
