<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: d3f22e92-6883-4c26-852b-c7a1ae81a498 */
/* Migration datetime: 2019-02-11 07:52:48.859711 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190211075248 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->uuid('location_id')->nullable(true);
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->foreign('location_id')->references('id')->on('locations');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropForeign('location_id');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('location_id');
    });
  }
}
