<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: d5039ed9-a894-49a7-a5ca-f3231c07abc2 */
/* Migration datetime: 2019-02-15 09:14:41.515520 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190215091441 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->integer('diff_qty')->nullable(true);
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->float('diff_value',20)->nullable(true);
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->integer('inhand_qty')->nullable(true);
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->float('inhand_value',20)->nullable(true);
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->integer('count_qty')->nullable(true)->unsigned();
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->float('count_value',20)->nullable(true)->unsigned();
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->float('cost',20)->nullable(true);
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->integer('inhand_qty')->nullable(true);
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->integer('count_qty')->nullable(true);
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->float('inhand_value',20)->nullable(true)->virtualAs('cost * inhand_qty');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->float('count_value',20)->nullable(true)->virtualAs('cost * count_qty');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->integer('diff_qty')->nullable(true)->virtualAs('count_qty - inhand_qty');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->float('diff_value',20)->nullable(true)->virtualAs('(cost * count_qty) - (cost * inhand_qty)');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('diff_value');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('diff_qty');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('count_value');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('inhand_value');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('count_qty');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('inhand_qty');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropColumn('cost');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('count_value');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('count_qty');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('inhand_value');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('inhand_qty');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('diff_value');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropColumn('diff_qty');
    });
  }
}
