<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 00d3ca91-7876-401e-8b0c-91122346d739 */
/* Migration datetime: 2019-02-28 10:10:29.760531 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190228101029 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {

    Schema::create('work_orders', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('number',250)->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('work_order_devices', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->uuid('work_order_id')->nullable(true);
      $table->uuid('device_id')->nullable(true);
      $table->text('device_details')->nullable(true);
      $table->uuid('device_type_id')->nullable(true);
      $table->text('issue_description')->nullable(true);
      $table->text('problem')->nullable(true);
      $table->text('solution')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('wodevice_parts', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->uuid('work_order_device_id')->nullable(true);
      $table->uuid('part_id')->nullable(true);
      $table->text('part_name')->nullable(true);
      $table->text('part_details')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('services', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('name',250);
      $table->text('details')->nullable(true);
      $table->float('selling_price_b2b')->nullable(true);
      $table->float('selling_price_b2c')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::create('wodevice_services', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->uuid('work_order_device_id')->nullable(true);
      $table->uuid('service_id')->nullable(true);
      $table->text('service_name')->nullable(true);
      $table->text('service_details')->nullable(true);
      $table->timestamp('created_at')->nullable(true);
      $table->timestamp('updated_at')->nullable(true);
    });
    Schema::table('work_order_devices', function (Blueprint $table) {
      $table->foreign('work_order_id')->references('id')->on('work_orders');
    });
    Schema::table('work_order_devices', function (Blueprint $table) {
      $table->foreign('device_id')->references('id')->on('devices');
    });
    Schema::table('work_order_devices', function (Blueprint $table) {
      $table->foreign('device_type_id')->references('id')->on('device_types');
    });
    Schema::table('wodevice_parts', function (Blueprint $table) {
      $table->foreign('work_order_device_id')->references('id')->on('work_order_devices');
    });
    Schema::table('wodevice_parts', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
    });
    Schema::table('wodevice_services', function (Blueprint $table) {
      $table->foreign('work_order_device_id')->references('id')->on('work_order_devices');
    });
    Schema::table('wodevice_services', function (Blueprint $table) {
      $table->foreign('service_id')->references('id')->on('services');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('wodevice_services', function (Blueprint $table) {
      $table->dropForeign(['service_id']);
    });
    Schema::table('wodevice_services', function (Blueprint $table) {
      $table->dropForeign(['work_order_device_id']);
    });
    Schema::table('wodevice_parts', function (Blueprint $table) {
      $table->dropForeign(['part_id']);
    });
    Schema::table('wodevice_parts', function (Blueprint $table) {
      $table->dropForeign(['work_order_device_id']);
    });
    Schema::table('work_order_devices', function (Blueprint $table) {
      $table->dropForeign(['device_type_id']);
    });
    Schema::table('work_order_devices', function (Blueprint $table) {
      $table->dropForeign(['device_id']);
    });
    Schema::table('work_order_devices', function (Blueprint $table) {
      $table->dropForeign(['work_order_id']);
    });
    Schema::dropIfExists('wodevice_services');
    Schema::dropIfExists('services');
    Schema::dropIfExists('wodevice_parts');
    Schema::dropIfExists('work_order_devices');
    Schema::dropIfExists('work_orders');
  }
}
