<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 0a5d057e-c1e9-4627-9bbc-31f8506af67d */
/* Migration datetime: 2019-02-07 11:21:09.392380 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190207112109 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::create('brands', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->string('name',255)->nullable(true);
      $table->multiLineString('description')->nullable(true);
      $table->uuid('manufacturer_id')->nullable(true);
      $table->unique(['id'],'brand_pk');
    });
    Schema::create('device_types', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('type',50);
      $table->unique(['id'],'device_type_pk');
    });
    Schema::create('devices', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->string('model_name',150)->unique();
      $table->multiLineString('details')->nullable(true);
      $table->uuid('brand_id')->nullable(true);
      $table->uuid('deviceType_id')->nullable(true);
      $table->char('model_number',200)->nullable(true);
      $table->unique(['id'],'devices_pk');
    });
    Schema::create('parts', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('sku',20)->unique();
      $table->multiLineString('details')->nullable(true);
      $table->uuid('partCategory_id')->nullable(true);
      $table->uuid('partStatus_id')->nullable(true);
      $table->uuid('partType_id')->nullable(true);
      $table->uuid('partColour_id')->nullable(true);
      $table->uuid('device_id')->nullable(true);
      $table->dateTime('first_received')->nullable(true);
      $table->string('part_name',200);
      $table->unique(['id'],'part_pk');
      $table->unique(['sku'],'sku');
      $table->index(['device_id'],'device_fk');
    });
    Schema::create('locations', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('location',100)->unique();
      $table->char('location_code',50)->unique();
      $table->multiLineString('description')->nullable(true);
      $table->unique(['id'],'location_pk');
    });
    Schema::create('part_statuses', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('status',50)->unique();
      $table->multiLineString('description')->nullable(true);
      $table->unique(['id'],'part_status_pk');
    });
    Schema::create('part_categories', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('category',100)->unique();
      $table->multiLineString('details')->nullable(true);
      $table->unique(['id'],'part_category_pk');
    });
    Schema::create('part_types', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('part_type',100)->unique();
      $table->multiLineString('details')->nullable(true);
      $table->unique(['id'],'part_type_pk');
    });
    Schema::create('part_stocks', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->uuid('part_id');
      $table->integer('stock_qty')->default(0);
      $table->uuid('location_id');
      $table->char('bin_location',100)->nullable(true);
      $table->integer('sold_all_time')->default(0);
      $table->unique(['id'],'part_stock_pk');
      $table->index(['part_id'],'part_id_fk');
    });
    Schema::create('part_prices', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->uuid('part_id')->nullable(true);
      $table->float('last_cost')->default(0.00);
      $table->float('selling_price_b2c')->default(0.00);
      $table->float('selling_price_b2b')->default(0.00);
      $table->unique(['id'],'part_price_pk');
      $table->index(['part_id'],'part_id_fk');
    });
    Schema::create('part_colours', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('colour',50)->unique();
      $table->unique(['id'],'part_colour_pk');
    });
    Schema::create('manufacturers', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('manufacturer',50)->unique();
      $table->unique(['id'],'manufacturer_pk');
      $table->unique(['manufacturer'],'manufacturer');
    });
    Schema::table('brands', function (Blueprint $table) {
      $table->foreign('manufacturer_id')->references('id')->on('manufacturers');
    });
    Schema::table('devices', function (Blueprint $table) {
      $table->foreign('brand_id')->references('id')->on('brands');
    });
    Schema::table('devices', function (Blueprint $table) {
      $table->foreign('deviceType_id')->references('id')->on('device_types');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('partCategory_id')->references('id')->on('part_categories');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('partStatus_id')->references('id')->on('part_statuses');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('partType_id')->references('id')->on('part_types');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('partColour_id')->references('id')->on('part_colours');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('device_id')->references('id')->on('devices');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->foreign('location_id')->references('id')->on('locations');
    });
    Schema::table('part_prices', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('part_prices', function (Blueprint $table) {
      $table->dropForeign('part_id');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->dropForeign('location_id');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->dropForeign('part_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('device_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('partColour_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('partType_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('partStatus_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('partCategory_id');
    });
    Schema::table('devices', function (Blueprint $table) {
      $table->dropForeign('deviceType_id');
    });
    Schema::table('devices', function (Blueprint $table) {
      $table->dropForeign('brand_id');
    });
    Schema::table('brands', function (Blueprint $table) {
      $table->dropForeign('manufacturer_id');
    });
    Schema::dropIfExists('manufacturers');
    Schema::dropIfExists('part_colours');
    Schema::dropIfExists('part_prices');
    Schema::dropIfExists('part_stocks');
    Schema::dropIfExists('part_types');
    Schema::dropIfExists('part_categories');
    Schema::dropIfExists('part_statuses');
    Schema::dropIfExists('locations');
    Schema::dropIfExists('parts');
    Schema::dropIfExists('devices');
    Schema::dropIfExists('device_types');
    Schema::dropIfExists('brands');
  }
}
