<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 25613995-8097-47b0-87d3-220e6bbe1a63 */
/* Migration datetime: 2019-02-08 14:39:00.572673 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190208143900 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::create('stock_count_statuses', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('status',50)->nullable(true)->unique();
      $table->unique(['id'],'stockcount_status_pk');
    });
    Schema::create('stock_counts', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->char('number',10)->unique();
      $table->timestamp('started_at')->useCurrent();
      $table->timestamp('ended_at')->nullable(true);
      $table->uuid('stockCountStatus_id')->nullable(true);
      $table->unique(['id'],'stock_count_pk');
    });
    Schema::create('stock_count_items_seqs', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->integer('qty')->nullable(true);
      $table->uuid('part_id')->nullable(true);
      $table->uuid('stockCount_id')->nullable(true);
      $table->unique(['id'],'stock_count_item_seq_pk');
    });
    Schema::create('stock_count_items', function (Blueprint $table) {
      $table->uuid('id')->unique();
      $table->integer('qty')->nullable(true);
      $table->uuid('stockCount_id')->nullable(true);
      $table->uuid('part_id')->nullable(true);
      $table->unique(['id'],'stock_count_items_pk');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->foreign('stockCountStatus_id')->references('id')->on('stock_count_statuses');
    });
    Schema::table('stock_count_items_seqs', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
    });
    Schema::table('stock_count_items_seqs', function (Blueprint $table) {
      $table->foreign('stockCount_id')->references('id')->on('stock_counts');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->foreign('stockCount_id')->references('id')->on('stock_counts');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropForeign('part_id');
    });
    Schema::table('stock_count_items', function (Blueprint $table) {
      $table->dropForeign('stockCount_id');
    });
    Schema::table('stock_count_items_seqs', function (Blueprint $table) {
      $table->dropForeign('stockCount_id');
    });
    Schema::table('stock_count_items_seqs', function (Blueprint $table) {
      $table->dropForeign('part_id');
    });
    Schema::table('stock_counts', function (Blueprint $table) {
      $table->dropForeign('stockCountStatus_id');
    });
    Schema::dropIfExists('stock_count_items');
    Schema::dropIfExists('stock_count_items_seqs');
    Schema::dropIfExists('stock_counts');
    Schema::dropIfExists('stock_count_statuses');
  }
}
