<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 5b3df17c-80c9-496e-90e0-70aeb124f434 */
/* Migration datetime: 2019-02-22 08:04:33.020162 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190222080433 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('device_parts', function (Blueprint $table) {
      $table->dropForeign('device_parts_device_id_foreign');
      $table->dropForeign('device_parts_part_id_foreign');
    });
    Schema::dropIfExists('device_parts');
    Schema::table('parts', function (Blueprint $table) {
      $table->uuid('device_id')->nullable(true);
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('device_id')->references('id')->on('devices');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('device_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropColumn('device_id');
    });
    Schema::create('device_parts', function (Blueprint $table) {
      $table->uuid('device_id');
      $table->uuid('part_id');
      $table->primary(['device_id','part_id']);
    });
    Schema::table('device_parts', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
      $table->foreign('device_id')->references('id')->on('devices');
    });
  }
}
