<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: c1b6fb80-8e21-4650-882c-312c9c742a2e */
/* Migration datetime: 2019-03-01 10:42:06.459702 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190301104206 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('purchase_order_items', function (Blueprint $table) {
      $table->boolean('is_edited')->default(0);
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('purchase_order_items', function (Blueprint $table) {
      $table->dropColumn('is_edited');
    });
  }
}
