<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: e241d428-27df-4a38-8912-6b221f579925 */
/* Migration datetime: 2019-02-22 08:13:45.114568 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190222081345 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('parts', function (Blueprint $table) {
      $table->uuid('parent_part_id')->nullable(true);
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->boolean('is_child')->nullable(true)->default(0);
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('parent_part_id')->references('id')->on('parts');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('parent_part_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropColumn('is_child');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropColumn('parent_part_id');
    });
  }
}
