<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 034ceba9-6eab-4b4c-a920-63505cf5588f */
/* Migration datetime: 2019-02-21 09:38:38.393251 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190221093838 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('suppliers', function (Blueprint $table) {
      $table->text('payment_details')->nullable(true)->change();
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('suppliers', function (Blueprint $table) {
      $table->multiLineString('payment_details')->nullable(true)->change();
    });
  }
}
