<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: 9fc6a476-e25d-4084-961a-388c8b3a6fc6 */
/* Migration datetime: 2019-02-21 10:55:47.019162 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190221105547 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('parts', function (Blueprint $table) {
      $table->dropForeign('device_id');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropIndex(device_fk);
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->dropColumn('device_id');
    });
    Schema::create('device_parts', function (Blueprint $table) {
      $table->uuid('device_id');
      $table->uuid('part_id');
      $table->primary(['device_id','part_id']);
    });
    Schema::table('device_parts', function (Blueprint $table) {
      $table->foreign('part_id')->references('id')->on('parts');
      $table->foreign('device_id')->references('id')->on('devices');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('device_parts', function (Blueprint $table) {
      $table->dropForeign('part_id');
      $table->dropForeign('device_id');
    });
    Schema::dropIfExists('device_parts');
    Schema::table('parts', function (Blueprint $table) {
      $table->uuid('device_id')->nullable(true);
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->index(['device_id'],'device_fk');
    });
    Schema::table('parts', function (Blueprint $table) {
      $table->foreign('device_id')->references('id')->on('devices');
    });
  }
}
