<?php
/* Migrations generated by: Skipper (http://www.skipper18.com) */
/* Migration id: c327a6f4-451e-4515-8208-f77b8a0777a8 */
/* Migration datetime: 2019-02-07 10:21:53.096653 */

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class Migrations20190207102153 extends Migration
{
  /**
   * Run the migrations.
   *
   * @return void
  */
  public function up()
  {
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->integer('stock_qty')->default(0)->change();
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->uuid('location_id')->unsigned()->change();
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->integer('sold_all_time')->default(0);
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->dropForeign('location_id');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->foreign('location_id')->references('id')->on('locations');
    });
  }
  /**
   * Reverse the migrations.
   *
   * @return void
  */
  public function down()
  {
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->dropForeign('location_id');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->foreign('location_id')->references('id')->on('locations');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->dropColumn('sold_all_time');
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->('location_id')->change();
    });
    Schema::table('part_stocks', function (Blueprint $table) {
      $table->('stock_qty')->default(0)->change();
    });
  }
}
